In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


Arrays in Numpy

In [2]:
import numpy as np

# creating array object
arr = np.array([[1,2,3],[4,6,7]])

print("Array is of type:",type(arr))
print("No. of dimentions:", arr.ndim)
print("Shape of array:", arr.shape)
print("Size of array:", arr.size)
print("Array stores elements of type:", arr.dtype)


Array is of type: <class 'numpy.ndarray'>
No. of dimentions: 2
Shape of array: (2, 3)
Size of array: 6
Array stores elements of type: int32


Numpy Array Creation

1. Create NumPy Array with List and Tuple

In [5]:
import numpy as np

a = np.array([[1,2,3],[5,8,7]], dtype= 'float')
print("Array created using passed List:\n", a)

b = np.array((1,3,2))
print("\nArray created using passed tuple:\n", b)

Array created using passed List:
 [[1. 2. 3.]
 [5. 8. 7.]]

Array created using passed tuple:
 [1 3 2]


2. Create Array of Fixed Size

In [8]:
c =  np.zeros((3,4))
print("\nAn array initialized with all zeros:\n", c)

d = np.full((3,3), 7, dtype='complex')
print("\nAn array initialized with all 7s. Array type is complex:\n", d)

e = np.random.random((2,2))
print("A random array:\n", e)


An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

An array initialized with all 7s. Array type is complex:
 [[7.+0.j 7.+0.j 7.+0.j]
 [7.+0.j 7.+0.j 7.+0.j]
 [7.+0.j 7.+0.j 7.+0.j]]
A random array:
 [[0.55555394 0.0586637 ]
 [0.0962291  0.44485267]]


3. Create Using arange() Function

In [12]:
f = np.arange(0,60,10)
print("\nA sequential array with steps of 10:\n", f)



A sequential array with steps of 10:
 [ 0 10 20 30 40 50]


4. Create Using linspace() Function

In [13]:
g = np.linspace(0,5,10)
print("\nA sequential array with 10 values between 0 and 5:\n", g)


A sequential array with 10 values between 0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


5. Reshaping Array using Reshape Method

In [14]:
arr = np.array([[1,2,3,4],
                [5,2,4,2],
                [1,2,0,1]])

newarr = arr.reshape(2,2,3)

print("Original array:\n", arr)
print("--------")
print("Reshaped array:\n", newarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
--------
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


6. Flatten Array

In [15]:
arr = np.array([[1,2,3],
                [4,5,6]])
flat_arr = arr.flatten()

print("Original array:\n", arr)
print("Flattened array:\n", flat_arr)

Original array:
 [[1 2 3]
 [4 5 6]]
Flattened array:
 [1 2 3 4 5 6]


NumPy Array Indexing


In [16]:
import numpy as np

arr = np.array([ [-1, 2, 0, 4],
                [4, -0.5, 6, 8],
                [7, 8, 9, 1.8],
                [3, -7, 4, 2.0]])

temp = arr[:2, ::2]
print("Array with first 2 rows and alternate columns(0 and 2):\n", temp)

temp = arr[[0,1,2,3], [3,2,1,0]]
print("\nElements at indices (0,3), (1,2), (2,1), (3,0):\n", temp)

cond = arr > 0
temp = arr[cond]
print("\nElements greater than 0:\n", temp)


Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (0,3), (1,2), (2,1), (3,0):
 [4. 6. 8. 3.]

Elements greater than 0:
 [2.  4.  4.  6.  8.  7.  8.  9.  1.8 3.  4.  2. ]


NumPy Basic Operations


In [18]:
# Operations on a single NumPy array

import numpy as np

a = np.array([1,2,5,3])

print("Adding 1 to every element:", a+1)
print("Subtracting 3 from each element:", a-3)
print("Multiplying each element by 5:", a*5)
print("Squaring each element:", a**2)

a*=2
print("Doubled each element of original array:", a)

a = np.array([[1,2,3],[3,4,5],[9,6,0]])

print("\nOriginal array:\n", a)
print("Transpose of array:\n", a.T)



Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 5: [ 5 10 25 15]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


NumPy – Unary Operators

In [19]:
import numpy as np

arr = np.array([[1,5,6],[4,7,2],[3,1,9]])

print("Largest element is:", arr.max())
print("Row-wise maximum elements:", arr.max(axis=1))

print("Column-wise minimum elements:", arr.min(axis=0))

print("Sum of all array elements:", arr.sum())

print("Cumulative sum along each row:\n", arr.cumsum(axis=1))

Largest element is: 9
Row-wise maximum elements: [6 7 9]
Column-wise minimum elements: [1 1 2]
Sum of all array elements: 38
Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


NumPy – Binary Operators

In [20]:
import numpy as np

a = np.array([[1,2],[3,4]])
b= np.array([[4,3],[2,1]])

print("Array sum:\n", a+b)
print("Array multiplication:\n", a*b)
print("Matrix multiplication:\n", a.dot(b))


Array sum:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]


NymPy’s ufuncs

In [21]:
import numpy as np

a = np.array([0,np.pi/2, np.pi])
print("Sine values of array elements:", np.sin(a))

a = np.array([0,1,2,3])
print("Exponent of array elements:", np.exp(a))

print("Square root of array elements:", np.sqrt(a))


Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


NumPy Sorting Arrays

In [23]:
import numpy as np

a = np.array([[1,4,2],[3,4,6],[0,-1,5]])

print("Array elements in sorted order:\n", np.sort(a, axis=None))

print("Row-wise sorted array:\n", np.sort(a, axis=1))

print("Column-wise sort by applying merge-sort:\n", np.sort(a, axis=0, kind='mergesort'))

dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]

values = [('Hansa', 2009, 8.5), ('Amal', 2008, 8.7), ('Pankajith', 2008, 7.9), ('Aakash', 2009, 9.0)]

arr =  np.array(values, dtype=dtypes)
print("\nArray sorted by names:\n", np.sort(arr, order='name'))

print("Array sorted by grauation year and then cgpa:\n", np.sort(arr, order=['grad_year', 'cgpa']))

Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]
Row-wise sorted array:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
Column-wise sort by applying merge-sort:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]

Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Amal', 2008, 8.7) (b'Hansa', 2009, 8.5)
 (b'Pankajith', 2008, 7.9)]
Array sorted by grauation year and then cgpa:
 [(b'Pankajith', 2008, 7.9) (b'Amal', 2008, 8.7) (b'Hansa', 2009, 8.5)
 (b'Aakash', 2009, 9. )]
